// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc-dev/go-avatar-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishAvatarDeleted provides a mock function with given fields: ctx, event
func (_m *MockEventPublisher) PublishAvatarDeleted(ctx context.Context, event domain.AvatarDeleteEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishAvatarDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AvatarDeleteEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishAvatarDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAvatarDeleted'
type MockEventPublisher_PublishAvatarDeleted_Call struct {
	*mock.Call
}

// PublishAvatarDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarDeleteEvent
func (_e *MockEventPublisher_Expecter) PublishAvatarDeleted(ctx interface{}, event interface{}) *MockEventPublisher_PublishAvatarDeleted_Call {
	return &MockEventPublisher_PublishAvatarDeleted_Call{Call: _e.mock.On("PublishAvatarDeleted", ctx, event)}
}

func (_c *MockEventPublisher_PublishAvatarDeleted_Call) Run(run func(ctx context.Context, event domain.AvatarDeleteEvent)) *MockEventPublisher_PublishAvatarDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AvatarDeleteEvent))
	})
	return _c
}

func (_c *MockEventPublisher_PublishAvatarDeleted_Call) Return(_a0 error) *MockEventPublisher_PublishAvatarDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishAvatarDeleted_Call) RunAndReturn(run func(context.Context, domain.AvatarDeleteEvent) error) *MockEventPublisher_PublishAvatarDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishAvatarUploaded provides a mock function with given fields: ctx, event
func (_m *MockEventPublisher) PublishAvatarUploaded(ctx context.Context, event domain.AvatarUploadEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishAvatarUploaded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AvatarUploadEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishAvatarUploaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAvatarUploaded'
type MockEventPublisher_PublishAvatarUploaded_Call struct {
	*mock.Call
}

// PublishAvatarUploaded is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarUploadEvent
func (_e *MockEventPublisher_Expecter) PublishAvatarUploaded(ctx interface{}, event interface{}) *MockEventPublisher_PublishAvatarUploaded_Call {
	return &MockEventPublisher_PublishAvatarUploaded_Call{Call: _e.mock.On("PublishAvatarUploaded", ctx, event)}
}

func (_c *MockEventPublisher_PublishAvatarUploaded_Call) Run(run func(ctx context.Context, event domain.AvatarUploadEvent)) *MockEventPublisher_PublishAvatarUploaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AvatarUploadEvent))
	})
	return _c
}

func (_c *MockEventPublisher_PublishAvatarUploaded_Call) Return(_a0 error) *MockEventPublisher_PublishAvatarUploaded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishAvatarUploaded_Call) RunAndReturn(run func(context.Context, domain.AvatarUploadEvent) error) *MockEventPublisher_PublishAvatarUploaded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
