// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc-dev/go-avatar-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockRepository) Create(ctx context.Context, a *domain.Avatar) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Avatar) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *domain.Avatar
func (_e *MockRepository_Expecter) Create(ctx interface{}, a interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, a *domain.Avatar)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Avatar))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Avatar) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByOwner provides a mock function with given fields: ctx, id, requestingUserID
func (_m *MockRepository) DeleteByOwner(ctx context.Context, id uuid.UUID, requestingUserID uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByOwner")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id, requestingUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id, requestingUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, requestingUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_DeleteByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByOwner'
type MockRepository_DeleteByOwner_Call struct {
	*mock.Call
}

// DeleteByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - requestingUserID uuid.UUID
func (_e *MockRepository_Expecter) DeleteByOwner(ctx interface{}, id interface{}, requestingUserID interface{}) *MockRepository_DeleteByOwner_Call {
	return &MockRepository_DeleteByOwner_Call{Call: _e.mock.On("DeleteByOwner", ctx, id, requestingUserID)}
}

func (_c *MockRepository_DeleteByOwner_Call) Run(run func(ctx context.Context, id uuid.UUID, requestingUserID uuid.UUID)) *MockRepository_DeleteByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_DeleteByOwner_Call) Return(_a0 *domain.Avatar, _a1 error) *MockRepository_DeleteByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_DeleteByOwner_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.Avatar, error)) *MockRepository_DeleteByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetCurrentByUserID(ctx context.Context, userID uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentByUserID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetCurrentByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentByUserID'
type MockRepository_GetCurrentByUserID_Call struct {
	*mock.Call
}

// GetCurrentByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetCurrentByUserID(ctx interface{}, userID interface{}) *MockRepository_GetCurrentByUserID_Call {
	return &MockRepository_GetCurrentByUserID_Call{Call: _e.mock.On("GetCurrentByUserID", ctx, userID)}
}

func (_c *MockRepository_GetCurrentByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_GetCurrentByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetCurrentByUserID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockRepository_GetCurrentByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetCurrentByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockRepository_GetCurrentByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockRepository_ListByUserID_Call {
	return &MockRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListByUserID_Call) Return(_a0 []*domain.Avatar, _a1 error) *MockRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Avatar, error)) *MockRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
