// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc-dev/go-avatar-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessingStatus provides a mock function with given fields: ctx, id, status, thumbs
func (_m *MockRepository) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus, thumbs map[string]string) error {
	ret := _m.Called(ctx, id, status, thumbs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProcessingStatus, map[string]string) error); ok {
		r0 = rf(ctx, id, status, thumbs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateProcessingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessingStatus'
type MockRepository_UpdateProcessingStatus_Call struct {
	*mock.Call
}

// UpdateProcessingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.ProcessingStatus
//   - thumbs map[string]string
func (_e *MockRepository_Expecter) UpdateProcessingStatus(ctx interface{}, id interface{}, status interface{}, thumbs interface{}) *MockRepository_UpdateProcessingStatus_Call {
	return &MockRepository_UpdateProcessingStatus_Call{Call: _e.mock.On("UpdateProcessingStatus", ctx, id, status, thumbs)}
}

func (_c *MockRepository_UpdateProcessingStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus, thumbs map[string]string)) *MockRepository_UpdateProcessingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.ProcessingStatus), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockRepository_UpdateProcessingStatus_Call) Return(_a0 error) *MockRepository_UpdateProcessingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateProcessingStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.ProcessingStatus, map[string]string) error) *MockRepository_UpdateProcessingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
