// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockImageResizer is an autogenerated mock type for the ImageResizer type
type MockImageResizer struct {
	mock.Mock
}

type MockImageResizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageResizer) EXPECT() *MockImageResizer_Expecter {
	return &MockImageResizer_Expecter{mock: &_m.Mock}
}

// ResizeToJPEG provides a mock function with given fields: ctx, src, width, height, quality
func (_m *MockImageResizer) ResizeToJPEG(ctx context.Context, src io.Reader, width int, height int, quality int) ([]byte, error) {
	ret := _m.Called(ctx, src, width, height, quality)

	if len(ret) == 0 {
		panic("no return value specified for ResizeToJPEG")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, int, int, int) ([]byte, error)); ok {
		return rf(ctx, src, width, height, quality)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, int, int, int) []byte); ok {
		r0 = rf(ctx, src, width, height, quality)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, int, int, int) error); ok {
		r1 = rf(ctx, src, width, height, quality)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageResizer_ResizeToJPEG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeToJPEG'
type MockImageResizer_ResizeToJPEG_Call struct {
	*mock.Call
}

// ResizeToJPEG is a helper method to define mock.On call
//   - ctx context.Context
//   - src io.Reader
//   - width int
//   - height int
//   - quality int
func (_e *MockImageResizer_Expecter) ResizeToJPEG(ctx interface{}, src interface{}, width interface{}, height interface{}, quality interface{}) *MockImageResizer_ResizeToJPEG_Call {
	return &MockImageResizer_ResizeToJPEG_Call{Call: _e.mock.On("ResizeToJPEG", ctx, src, width, height, quality)}
}

func (_c *MockImageResizer_ResizeToJPEG_Call) Run(run func(ctx context.Context, src io.Reader, width int, height int, quality int)) *MockImageResizer_ResizeToJPEG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(int), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockImageResizer_ResizeToJPEG_Call) Return(_a0 []byte, _a1 error) *MockImageResizer_ResizeToJPEG_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageResizer_ResizeToJPEG_Call) RunAndReturn(run func(context.Context, io.Reader, int, int, int) ([]byte, error)) *MockImageResizer_ResizeToJPEG_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageResizer creates a new instance of MockImageResizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageResizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageResizer {
	mock := &MockImageResizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
