package avatar

import (
	"io"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/avc-dev/go-avatar-service/internal/httpx"
	svcavatar "github.com/avc-dev/go-avatar-service/internal/services/avatar"
)

// Download handles GET /api/v1/avatars/{avatar_id}.
//
// The ?size query parameter selects which binary to return:
//   - empty or "original" → the originally uploaded file
//   - "100x100", "300x300", etc. → the matching thumbnail (404 if not yet
//     generated by the worker)
//
// Headers must be set BEFORE the first Write — once io.Copy starts, the
// response is committed with the implicit 200 OK. The ?format query parameter
// from the spec is accepted but ignored: thumbnails are always JPEG and the
// original is served in its uploaded format.
func (h *Handler) Download(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	id, err := uuid.Parse(chi.URLParam(r, "avatar_id"))
	if err != nil {
		httpx.WriteError(w, http.StatusBadRequest, "avatar_id must be a valid UUID", err.Error())
		return
	}

	size := r.URL.Query().Get("size")

	var result *svcavatar.DownloadResult
	if size == "" || size == "original" {
		result, err = h.svc.DownloadOriginal(ctx, id)
	} else {
		result, err = h.svc.DownloadThumbnail(ctx, id, size)
	}
	if err != nil {
		status, msg := mapServiceError(err)
		if status >= 500 {
			h.log.Error("download: service call failed", "err", err, "avatar_id", id, "size", size)
		}
		httpx.WriteError(w, status, msg)
		return
	}
	defer func() { _ = result.Reader.Close() }()

	w.Header().Set("Content-Type", result.ContentType)
	w.Header().Set("Content-Length", strconv.FormatInt(result.Size, 10))

	if _, err := io.Copy(w, result.Reader); err != nil {
		// Headers and the implicit 200 OK are already on the wire — we cannot
		// change the status now. Log a WARN so the partial transfer is
		// observable in operational logs.
		h.log.Warn("download: copy to response writer failed mid-stream",
			"err", err,
			"avatar_id", id,
		)
	}
}
