// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/avc-dev/go-avatar-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	servicesavatar "github.com/avc-dev/go-avatar-service/internal/services/avatar"

	uuid "github.com/google/uuid"
)

// MockAvatarService is an autogenerated mock type for the AvatarService type
type MockAvatarService struct {
	mock.Mock
}

type MockAvatarService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarService) EXPECT() *MockAvatarService_Expecter {
	return &MockAvatarService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id, requestingUserID
func (_m *MockAvatarService) Delete(ctx context.Context, id uuid.UUID, requestingUserID uuid.UUID) error {
	ret := _m.Called(ctx, id, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, requestingUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAvatarService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - requestingUserID uuid.UUID
func (_e *MockAvatarService_Expecter) Delete(ctx interface{}, id interface{}, requestingUserID interface{}) *MockAvatarService_Delete_Call {
	return &MockAvatarService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, requestingUserID)}
}

func (_c *MockAvatarService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, requestingUserID uuid.UUID)) *MockAvatarService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_Delete_Call) Return(_a0 error) *MockAvatarService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockAvatarService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCurrentByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAvatarService) DeleteCurrentByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCurrentByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarService_DeleteCurrentByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCurrentByUserID'
type MockAvatarService_DeleteCurrentByUserID_Call struct {
	*mock.Call
}

// DeleteCurrentByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAvatarService_Expecter) DeleteCurrentByUserID(ctx interface{}, userID interface{}) *MockAvatarService_DeleteCurrentByUserID_Call {
	return &MockAvatarService_DeleteCurrentByUserID_Call{Call: _e.mock.On("DeleteCurrentByUserID", ctx, userID)}
}

func (_c *MockAvatarService_DeleteCurrentByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAvatarService_DeleteCurrentByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_DeleteCurrentByUserID_Call) Return(_a0 error) *MockAvatarService_DeleteCurrentByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarService_DeleteCurrentByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAvatarService_DeleteCurrentByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadOriginal provides a mock function with given fields: ctx, id
func (_m *MockAvatarService) DownloadOriginal(ctx context.Context, id uuid.UUID) (*servicesavatar.DownloadResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DownloadOriginal")
	}

	var r0 *servicesavatar.DownloadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*servicesavatar.DownloadResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *servicesavatar.DownloadResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesavatar.DownloadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_DownloadOriginal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadOriginal'
type MockAvatarService_DownloadOriginal_Call struct {
	*mock.Call
}

// DownloadOriginal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarService_Expecter) DownloadOriginal(ctx interface{}, id interface{}) *MockAvatarService_DownloadOriginal_Call {
	return &MockAvatarService_DownloadOriginal_Call{Call: _e.mock.On("DownloadOriginal", ctx, id)}
}

func (_c *MockAvatarService_DownloadOriginal_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarService_DownloadOriginal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_DownloadOriginal_Call) Return(_a0 *servicesavatar.DownloadResult, _a1 error) *MockAvatarService_DownloadOriginal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_DownloadOriginal_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*servicesavatar.DownloadResult, error)) *MockAvatarService_DownloadOriginal_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadThumbnail provides a mock function with given fields: ctx, id, size
func (_m *MockAvatarService) DownloadThumbnail(ctx context.Context, id uuid.UUID, size string) (*servicesavatar.DownloadResult, error) {
	ret := _m.Called(ctx, id, size)

	if len(ret) == 0 {
		panic("no return value specified for DownloadThumbnail")
	}

	var r0 *servicesavatar.DownloadResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*servicesavatar.DownloadResult, error)); ok {
		return rf(ctx, id, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *servicesavatar.DownloadResult); ok {
		r0 = rf(ctx, id, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicesavatar.DownloadResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_DownloadThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadThumbnail'
type MockAvatarService_DownloadThumbnail_Call struct {
	*mock.Call
}

// DownloadThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - size string
func (_e *MockAvatarService_Expecter) DownloadThumbnail(ctx interface{}, id interface{}, size interface{}) *MockAvatarService_DownloadThumbnail_Call {
	return &MockAvatarService_DownloadThumbnail_Call{Call: _e.mock.On("DownloadThumbnail", ctx, id, size)}
}

func (_c *MockAvatarService_DownloadThumbnail_Call) Run(run func(ctx context.Context, id uuid.UUID, size string)) *MockAvatarService_DownloadThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockAvatarService_DownloadThumbnail_Call) Return(_a0 *servicesavatar.DownloadResult, _a1 error) *MockAvatarService_DownloadThumbnail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_DownloadThumbnail_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*servicesavatar.DownloadResult, error)) *MockAvatarService_DownloadThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAvatarService) GetCurrentByUserID(ctx context.Context, userID uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentByUserID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_GetCurrentByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentByUserID'
type MockAvatarService_GetCurrentByUserID_Call struct {
	*mock.Call
}

// GetCurrentByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAvatarService_Expecter) GetCurrentByUserID(ctx interface{}, userID interface{}) *MockAvatarService_GetCurrentByUserID_Call {
	return &MockAvatarService_GetCurrentByUserID_Call{Call: _e.mock.On("GetCurrentByUserID", ctx, userID)}
}

func (_c *MockAvatarService_GetCurrentByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAvatarService_GetCurrentByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_GetCurrentByUserID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockAvatarService_GetCurrentByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_GetCurrentByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockAvatarService_GetCurrentByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function with given fields: ctx, id
func (_m *MockAvatarService) GetMetadata(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockAvatarService_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarService_Expecter) GetMetadata(ctx interface{}, id interface{}) *MockAvatarService_GetMetadata_Call {
	return &MockAvatarService_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx, id)}
}

func (_c *MockAvatarService_GetMetadata_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarService_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_GetMetadata_Call) Return(_a0 *domain.Avatar, _a1 error) *MockAvatarService_GetMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_GetMetadata_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockAvatarService_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAvatarService) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockAvatarService_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAvatarService_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockAvatarService_ListByUserID_Call {
	return &MockAvatarService_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockAvatarService_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAvatarService_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarService_ListByUserID_Call) Return(_a0 []*domain.Avatar, _a1 error) *MockAvatarService_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_ListByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Avatar, error)) *MockAvatarService_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, p
func (_m *MockAvatarService) Upload(ctx context.Context, p servicesavatar.UploadParams) (*domain.Avatar, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, servicesavatar.UploadParams) (*domain.Avatar, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, servicesavatar.UploadParams) *domain.Avatar); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, servicesavatar.UploadParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockAvatarService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - p servicesavatar.UploadParams
func (_e *MockAvatarService_Expecter) Upload(ctx interface{}, p interface{}) *MockAvatarService_Upload_Call {
	return &MockAvatarService_Upload_Call{Call: _e.mock.On("Upload", ctx, p)}
}

func (_c *MockAvatarService_Upload_Call) Run(run func(ctx context.Context, p servicesavatar.UploadParams)) *MockAvatarService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(servicesavatar.UploadParams))
	})
	return _c
}

func (_c *MockAvatarService_Upload_Call) Return(_a0 *domain.Avatar, _a1 error) *MockAvatarService_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarService_Upload_Call) RunAndReturn(run func(context.Context, servicesavatar.UploadParams) (*domain.Avatar, error)) *MockAvatarService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAvatarService creates a new instance of MockAvatarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarService {
	mock := &MockAvatarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
